// internal/domain/error/error.go (additional errors)
package errs

import "errors"

// Existing errors...
var ErrNegativeAmount = errors.New("amount cannot be negative")
var ErrInsufficientBalance = errors.New("insufficient balance")
var ErrExpiredTransaction = errors.New("transaction expired")
var ErrNotFound = errors.New("not found")
var ErrTransactionNotVerified = errors.New("transaction is not in 'verified' status")
var ErrAmountExceedsLimit = errors.New("amount exceeds maximum limit")
var ErrInvalidPaymentMethod = errors.New("invalid payment method")
var ErrInvalidTransactionStatus = errors.New("invalid transaction status")
var ErrInvalidUserRole = errors.New("invalid user role")

// POS system errors
var ErrInvalidOrderStatus = errors.New("invalid order status")
var ErrInvalidCategoryType = errors.New("invalid category type")
var ErrInvalidTableNumber = errors.New("invalid table number")
var ErrInvalidQuantity = errors.New("invalid quantity")
var ErrInsufficientQuantity = errors.New("insufficient quantity")
var ErrOrderNotFound = errors.New("order not found")
var ErrOrderAlreadyClosed = errors.New("order already closed")
var ErrOrderNotOpen = errors.New("order is not open")
var ErrOrderNotClosed = errors.New("order is not closed")
var ErrTableNotFound = errors.New("table not found")
var ErrMenuItemNotFound = errors.New("menu item not found")
var ErrCategoryNotFound = errors.New("category not found")
var ErrDuplicateTableNumber = errors.New("duplicate table number")
var ErrDuplicateCategoryName = errors.New("duplicate category name")
var ErrOrderItemNotFound = errors.New("order item not found")
var ErrPaymentNotFound = errors.New("payment not found")
var ErrPaymentAlreadyExists = errors.New("payment already exists")
var ErrInvalidPaymentAmount = errors.New("invalid payment amount")
var ErrInvalidQRCode = errors.New("invalid QR code")
var ErrTableAlreadyHasOpenOrder = errors.New("table already has an open order")
var ErrCannotDeleteCategoryWithItems = errors.New("cannot delete category with existing menu items")
var ErrCannotDeleteTableWithOrders = errors.New("cannot delete table with existing orders")
var ErrEmptyOrder = errors.New("order has no items")
var ErrInvalidDateRange = errors.New("invalid date range")
var ErrInvalidRevenueDate = errors.New("invalid revenue date")

// Additional business logic errors
var ErrMenuItemOutOfStock = errors.New("menu item is out of stock")
var ErrInvalidMenuItemPrice = errors.New("invalid menu item price")
var ErrInvalidTableSeating = errors.New("invalid table seating capacity")
var ErrOrderItemAlreadyExists = errors.New("order item already exists")
var ErrCannotModifyClosedOrder = errors.New("cannot modify closed order")
var ErrInvalidOrderItemQuantity = errors.New("invalid order item quantity")
var ErrMaxOrderItemsExceeded = errors.New("maximum order items exceeded")
var ErrInvalidCategoryForMenuItem = errors.New("invalid category for menu item")
var ErrCannotDeleteActiveMenuItem = errors.New("cannot delete active menu item")
var ErrTableNotAvailable = errors.New("table is not available")
var ErrInvalidReservationTime = errors.New("invalid reservation time")
var ErrPrinterNotAvailable = errors.New("printer is not available")
var ErrInvalidReceiptFormat = errors.New("invalid receipt format")
var ErrStockNotAvailable = errors.New("stock is not available")
var ErrInvalidStockQuantity = errors.New("invalid stock quantity")
var ErrReservationExpired = errors.New("reservation has expired")
var ErrInvalidDiscountAmount = errors.New("invalid discount amount")
var ErrDiscountNotApplicable = errors.New("discount is not applicable")
var ErrInvalidTaxRate = errors.New("invalid tax rate")
var ErrServiceChargeNotApplicable = errors.New("service charge is not applicable")
var ErrInvalidOrderTime = errors.New("invalid order time")
var ErrKitchenNotAvailable = errors.New("kitchen is not available")
var ErrInvalidMenuCategory = errors.New("invalid menu category")
var ErrInvalidBusinessHours = errors.New("operation outside business hours")
var ErrTableCapacityExceeded = errors.New("table capacity exceeded")
var ErrInvalidCustomerCount = errors.New("invalid customer count")
var ErrWaitingListFull = errors.New("waiting list is full")
var ErrInvalidWaitingTime = errors.New("invalid waiting time")
var ErrInvalidOrderNote = errors.New("invalid order note")
var ErrInvalidSpecialRequest = errors.New("invalid special request")
var ErrInvalidPromoCode = errors.New("invalid promo code")
var ErrPromoCodeExpired = errors.New("promo code has expired")
var ErrPromoCodeAlreadyUsed = errors.New("promo code already used")
var ErrInvalidLoyaltyPoints = errors.New("invalid loyalty points")
var ErrInsufficientLoyaltyPoints = errors.New("insufficient loyalty points")
